version: '3'
services:
  tomcat-img:
    image: 'tomcat:9'
    ports:
    - "8080:8080"
    volumes:
    - "/opt/war:/usr/local/tomcat/webapps"

    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: admin

    depends_on:
    - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
    - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
