version: '3'
services:
  tomcat-img:
    image: 'tomcat:9'
    ports:
    - "8080:8080"
    volumes:
    - "/opt/war:/usr/local/tomcat/webapps"

    depends_on:
    - mysql

  mysql:
    image: mysql:latest
    ports:
    - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
